"""feat: add Base, User, UserAchievement, UserStats, Achievement, Game, Level ORM models

Revision ID: e49729c6ebc2
Revises: 
Create Date: 2025-08-25 01:19:44.262506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49729c6ebc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('shortDescription', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('requiredScore', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegramId', sa.BigInteger(), nullable=False),
    sa.Column('chatId', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatId'),
    sa.UniqueConstraint('telegramId')
    )
    op.create_table('achievements',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conditionKey', sa.String(length=100), nullable=False),
    sa.Column('conditionValue', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stats',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('levelId', sa.Integer(), nullable=False),
    sa.Column('totalScore', sa.Integer(), nullable=False),
    sa.Column('totalGamesPlayed', sa.Integer(), nullable=False),
    sa.Column('learnMode', sa.Integer(), nullable=False),
    sa.Column('creativeMode', sa.Integer(), nullable=False),
    sa.Column('codeMode', sa.Integer(), nullable=False),
    sa.Column('antiPromptMode', sa.Integer(), nullable=False),
    sa.Column('puzzleMode', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['levelId'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_achievements',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('achievementId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievementId'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'achievementId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    op.drop_table('user_stats')
    op.drop_table('achievements')
    op.drop_table('users')
    op.drop_table('levels')
    op.drop_table('games')
    # ### end Alembic commands ###
